Kossy3/100kill

- Assets/Scripts/Enemy.cs
- Assets/Scripts/Enemy.cs.meta
- Assets/Scripts/KeyInputManager.cs
- Assets/Scripts/KeyInputManager.cs.meta
- Assets/Scripts/Player.cs
- Assets/Scripts/Player.cs.meta
> KeyInputManager, Enemy, Player の空スクリプト追加

- Assets/Scripts/Database.cs
- Assets/Scripts/RythmGenerator.cs
RhythmGeneratorに「ステージ１，２では、スライディングとジャンプできない」という機能を追加
> RhythmGeneratorの編集

- Assets/Scripts/Database.cs
#32
defeat_count変数の追加（int型、初期値０）
> defeat_count変数の追加

- Assets/Scripts/Enemy.cs
- Assets/Scripts/KeyInputManager.cs
- Logs/ApiUpdaterCheck.txt
> 敵が画面外に移動したら消えるようにしました

- Assets/Scripts/KeyInputManager.cs
> 押された瞬間のみ判定するように変更しました。

- Assets/Prefabs/enemy1.prefab
- Assets/Prefabs/enemy1.prefab.meta
> playerの位置を移動、敵のプレハブを作りました

- Assets/Prefabs/enemy1.prefab
- Assets/Prefabs/enemy1.prefab.meta
- Assets/Scenes/Main.unity
- Assets/Scripts/Enemy.cs
- Logs/ApiUpdaterCheck.txt
> M move enemy

- Assets/Prefabs/enemy1.prefab
- Assets/Scenes/Main.unity
> enemyのプレハブをぶっ壊したので作り直しました

- Assets/Scenes/Main.unity
- Assets/Scripts/Database.cs
- Assets/Scripts/TimingManager.cs
TimingManagerの編集
　PlayerのKey入力によるAnimetionの起動処理
　Good,Missの判定処理
TimingManagerのInspectorの変更
> S edit timing manager

- Assets/Scripts/CountDown.cs
- Assets/Scripts/DefeatCount.cs
- Assets/Scripts/DefeatCount.cs.meta
#59 
倒した敵の数を漢数字で画面中央上部に表記
Timerと同じく修正の可能性あり
> DefeatCountの作成、Timerの修正

- Assets/Scripts/Enemy.cs
- Logs/ApiUpdaterCheck.txt
> enemyの速度がfloatで処理されるよう変更

- Assets/Scenes/Main.unity
- Assets/Scripts/Database.cs
- Assets/Scripts/DefeatCount.cs
defeat_color_nnumberのLsitの定義
add_defeat_color_numberのmethedの定義
color_listの定義とInspectorの編集
> Databaseの編集

- Assets/Scenes/Main.unity
- Assets/Scripts/Enemy.cs
Playerの位置調整
Enemyの速度調整
TimingManagerのInspectorの修正
> 作業ミスの修正、調整

- Assets/Scripts/Timer.cs
- Assets/Scripts/TimingManager.cs
#65 
Rhythmによる出現する敵の仕分けするシステムの作成
> TimingManagerの編集

- Assets/Images/enemy/enemy0/enemy0.controller
- Assets/Prefabs/enemy1.prefab
- Assets/Prefabs/enemy1_0.prefab
- Assets/Prefabs/enemy1_3.prefab
- Assets/Prefabs/enemy_2.prefab
- Assets/Prefabs/stone.prefab
- Assets/Prefabs/upthing.prefab
- Assets/Scenes/Main.unity
- ProjectSettings/TagManager.asset
> playerとenemyのレイヤーを変更しました

- Assets/Scripts/Database.cs
- Assets/Scripts/Defeats.cs
- Assets/Scripts/MusicGenerator.cs
- Assets/Scripts/TimingManager.cs
#67
TimingManagerの修正
　RhythmGeneratorから生成したRhythmをMusicGeneratorに渡し、Scoreを生成
　→ScoreをMusicPlayerに渡し音を出す。
　（一小節分 - MusicPlayerが音生成するまでのラグ分）だけ音のずれを確認。要修正。
> TimingManagerから音楽を生成できるように修正

- Assets/Images/enemy/enemy0/enemy0.controller
- Assets/Images/enemy/enemy0/enemy_finish0.anim
- Assets/Images/enemy/enemy0/enemy_finish0.anim.meta
- Assets/Images/enemy/enemy0/enemy_yarare0.anim
- Assets/Images/enemy/enemy1/enemy1.controller
- Assets/Images/enemy/enemy1/enemy_finish1.anim
- Assets/Images/enemy/enemy1/enemy_finish1.anim.meta
- Assets/Images/enemy/enemy1/enemy_yarare 1.anim
- Assets/Images/enemy/enemy2/enemy2.controller
- Assets/Images/enemy/enemy2/enemy_finish2.anim
- Assets/Images/enemy/enemy2/enemy_finish2.anim.meta
- Assets/Images/enemy/enemy2/enemy_yarare2.anim
- Assets/Images/enemy/enemy3/enemy3.controller
- Assets/Images/enemy/enemy3/enemy_finish3.anim
- Assets/Images/enemy/enemy3/enemy_finish3.anim.meta
- Assets/Scenes/Main.unity
- Assets/Scripts/Enemy.cs
> enemyの修正とanimationの修正、skillgaugeを少し変えました

- Assets/Scenes/Main.unity
- Assets/Scripts/CountDown.cs
- Assets/Scripts/Defeats.cs
- Assets/Scripts/StopMenu.cs
- Assets/Scripts/StopMenu.cs.meta
- ProjectSettings/TagManager.asset
#99
Stopmenuの作成
　Escapキー入力で一時停止
　A,S,Dで選択orマウスをボタンの上に置くことで、選択肢を選べる
　決定はSpaceキーの入力orマウスクリック
　SceneSettingができていないためStartのSceneへの移動でエラー
　ストップ時に、Playerのアニメーションが動いてしまうためKeyInputManagerのUpdateで
　if (Time.timeScale == 1) の条件でKey入力判定をとらないといけないかも
> StopMenuの作成

- Assets/Scenes/Score.unity
- Assets/Scenes/Score.unity.meta
- Assets/Scripts/Database.cs
- Assets/Scripts/Defeats.cs
#104
Databaseの修正
　Start()内にDontDestroyOnLord()を追加
　public void reset()を追加
　　BGM,defeated_enemies,defeated_color_number,Stages,HP,skill_gaugeを初期化
　HP == 0の時に読み込むSceneを"Start"から”Score”へ
Scene"Score"の追加
　スコアを表示するSceneとして"Score"を追加。（張りぼて）
> Detabaseの修正、Scene"Score"の追加

- Assets/Scenes/Start.unity
- Assets/Scripts/StartGame.cs
- Assets/Scripts/StartGame.cs.meta
- Assets/Scripts/StopMenu.cs
- ProjectSettings/EditorBuildSettings.asset
- UserSettings/EditorUserSettings.asset
Scene"Start"の作成
　Spaceキーの入力or「開始」をマウスクリックでScene”Main”へ。
　今後、Scene”Score”への移動ボタンやキーの設定を行うかも。
　DatabaseがScene移動の度に増殖。Scene移動前にDestroyすることに。もしかしたらDatabaseのresetは不要かも。
BuiltSettingの編集
　BuiltSettingに３つのSceneの登録。
> Scene"Start"の作成、BuiltSettingの編集

- Assets/Scripts/Database.cs
- Assets/Scripts/TimingManager.cs
#109 
　Stageが上がった後の、前Stageの敵の判定が取れないバグ
　敵が一定間隔出現しないときにエラーが出るバグ
　BGMの上昇およびskill_gaugeの回復がい一小節分早いバグ
　Key入力をしないとそれ以降の敵の判定が取れなくなるバグ　を修正
> TimingManager周りのバグ修正

- Assets/Scripts/Enemy.cs
> 判定がmissになったらHPが減少するようにしました

- Assets/Scripts/Enemy.cs
> HPの処理を直しました

- Assets/Scripts/SceneNavigator.cs
- UserSettings/EditorUserSettings.asset
#132 
　Keyの割り振りは一旦Tabキーに
　そのほか、A,Sキー、マウス操作などで選択可能
> Start画面下のButtonを作成

- Assets/Scripts/TimingManager.cs
#135 
　スライディングには、Upthingを
　ジャンプには、Stoneを
　出現できるように変更
> Key対応ずれの修正

- Assets/Scenes/Method.unity
> WキーとSキーが逆だったので直しました

- Assets/Scenes/Start.unity
- Assets/Scripts/SceneNavigator.cs
> どちらのAltキーも反応するようにしました

- Assets/Scenes/Score.unity
- Assets/Scripts/BackStartScene.cs
- Assets/Scripts/Database.cs
- Assets/Scripts/ModeChanger.cs
- Assets/Scripts/MyScore.cs
- Assets/Scripts/RankingTable.cs
- Assets/Scripts/SceneNavigator.cs
- Assets/Scripts/WarningBoard.cs
- Assets/Scripts/WarningBoard.cs.meta
- Assets/prefabs/Flame.prefab
#151 
プレイヤーネームの重複を可能に
　一応、できるだけ重複はしないように警告をつける
無記名の場合は「Guest」としてランキングに表示
　一度シーンから出ると削除されるように
　オンライン化した際もサーバーに登録しないように
　これも警告を出す
> プレイヤーネームの重複を可能に
